- name: Deploy to Linux
  uses: appleboy/ssh-action@v1
  with:
    host: ${{ secrets.SERVER_HOST }}
    username: ${{ secrets.SERVER_USER }}
    key: ${{ secrets.SERVER_SSH_KEY }}
    script: |
      docker pull ${{ secrets.DOCKER_USERNAME }}/mouldprodfrontend:latest

      docker stop MouldProduct || true
      docker rm MouldProduct || true

      docker run -d -p 127.0.0.1:8088:80 \
        --name MouldProduct \
        --restart unless-stopped \
        ${{ secrets.DOCKER_USERNAME }}/mouldprodfrontend:latest